### PR TITLE
Fix bugs, crashes, update 'your library' page & more

### LINKED ISSUE #21: [Bug Report] Art cover and proper username doesn't show up my own playlists in the library section
### Describe the bug

If I go to the library section a look at my own playlists, it doesn't show the art cover and instead of displaying the name  of the author for the playlist it displays what appear to be a uuid instead.

### To Reproduce

_No response_

### Error reports & Screenshots

Screenshot_20240108-103441

### Device info

Device: Google Pixel 7
OS: Android 14 (stock)
Jetispot ver: 0.1.6

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Outlet7493**
Changes made:
- Update dependencies
- Fix A14/SDK 34 crash missing `FOREGROUND_SERVICE_MEDIA_PLAYBACK` permission
- HTML playlist description support - some playlists (e.g. Spotify's daylist feature) have HTML descriptions with links in them
- Fix https://github.com/BobbyESP/Jetispot/issues/21 (and as described in the issue):
  - Fixed username issue
  - Applied (temporary?) workaround to save playlist image if seen on home screen or returned from API when in playlist view
- Implement https://github.com/BobbyESP/Jetispot/issues/9
  - Bottom sheet now has rounded corners at the top
  - Navbar only shows label of selected tab
- Your library changes:
  - Fetch stored user profile image (to replace blank default one)
  - Match style to home screen
  - Implement search feature
  - Add support for "Your Episodes" entry instead of empty pinned playlist (screen itself still needs made)
  - Add support for pinned playlists
  - Remove duplicate and empty 
- Add support for `PromoCardHomeComponent.proto`
- Fix crash when pressing play on album from home screen (haven't yet fixed the issue where playback doesn't start, but it no longer crashes)
- Manually place album/playlist art on card (e.g. card on search screen) as the API returns just a color as the background image sometimes, so it now uses the main URI and moves it into place

Also I think https://github.com/BobbyESP/Jetispot/issues/13 can be closed now too.

### CODE REVIEW

**Comment by BobbyESP** [comment]
Hi! First of all I want to thank you for the hard work in the project :). It's really nice to see people interested on helping, for real.

Leaving that at one side, I will be taking a look to the PR changes this afternoon (if I have time since I'm with exams) for reviewing all the changes.

If all it's good I will merge the PR in the main branch and, after that, the next step will be migrating to Media3 and rebuild the playback system since it's kinda broken 😂. It works, but not really good. The same with lyrics

**Comment by BobbyESP** [comment]
Closed #13 since it was already fixed

**Review by BobbyESP — APPROVED** [review]
For me all seems okay! Really thanks for your amazing job! If you have planned to do more work I'll wait, if not, gonna merge it to main branch

**Comment by Outlet7493** [comment]
No problem! Happy I can help - used Jetispot off and on from before this fork so been wanting to contribute for a while.

Thanks for reviewing PR during exams! Those are definitely more important :smile: 

I am happy for this to be merged now... not sure what to work on next just yet. Had a little look at Media3 migration and looks like a bigger task than I was anticipating (never migrated, only used Media3/ExoPlayer by itself) but more than happy to help out with it if you need a hand.

**Comment by BobbyESP** [comment]
Thanks mate and don't worry about Media3, it can wait. Google has a script that helps us to migrate the project automatically, so it may not be very hard. I still don't understand really well how Media3 works, a lot of things to touch at the same time and without good documentation... I think I will have to create a library for help with this

**Comment by BobbyESP** [comment]
Another time really thanks for the work you have put at the PR!

**Pull request merged**
